"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ybcim6=@)la&g9@!asz1rx95=qd&39$tl1j1(1uflb_$mo*w##'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*'
    ]


# Application definition

INSTALLED_APPS = [
    # 'app.admin.admin_site',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'django_celery_beat',
    'rangefilter',
    'django_admin_listfilter_dropdown'
    # 'rest_framework',
    # 'django_restful_admin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#         'default':{
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'check_youtube',
#         'USER': 'administrator',
#         'PASSWORD': 'bangtin_ainews_2811#',
#         'HOST': '103.192.236.67',
#         'PORT': '',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT= BASE_DIR + '/static/'
STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR + '/media'
MEDIA_URL = '/media/'

# CELERY BEAT
CELERY_BROKER_URL = 'redis://localhost:6379'
# If time zones are active (USE_TZ = True) define your local
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
# app.conf.enable_utc = False # so celery doesn't take utc by default

# CELERY_BEAT_SCHEDULE = {

#     # Track Publisher check publisher channel to get new videos
#     'track_publisher': {
#        'task': 'track_publisher',
#         # There are 4 ways we can handle time, read further
#         # TODO: raise schedule time to 300 (5 minutes) in production
#        'schedule': 300,
#         # If you're using any arguments
#        'args': (),
#     },

#     # Track Topic check topic on youtube to get new videos & new publisher
#     'track_topic': {
#        'task': 'track_topic',
#         # There are 4 ways we can handle time, read further
#         # TODO: raise schedule time to 300 (5 minutes) in production
#        'schedule': 300,
#         # If you're using any arguments
#        'args': (),
#     },


#     # Check VIP Mention check all video to detect new VIP mentions
#     'check_VIP_mention': {
#        'task': 'check_VIP_mention',
#        'schedule': 180,
#        'args': (),
#     },

#     # Parse Youtube clip to get its content from speech
#     'parse_youtube_clip_to_text': {
#        'task': 'parse_youtube_clip_to_text',
#        'schedule': 300,
#        'args': (),
#     },

#     # Parse Youtube clip to get its content from speech
#     'check_youtube_live_status': {
#        'task': 'check_youtube_live_status',
#        'schedule': 3600,
#        'args': (),
#     },



# }

CELERY_MAX_TASKS_PER_CHILD = 100 # restart worker on this max task to avoid memory leak
