# Generated by Django 3.0.3 on 2020-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.TextField(blank=True, default='', verbose_name='STT')),
                ('group', models.TextField(blank=True, default='', verbose_name='Tên nhóm')),
                ('classify', models.TextField(blank=True, default='', verbose_name='Loại')),
                ('url', models.URLField(default='', null=True, verbose_name='Đường Link')),
                ('views', models.TextField(default='', verbose_name='Lượt xem')),
                ('publish_date', models.DateTimeField(null=True, verbose_name='Thời gian đăng')),
                ('send_date', models.DateTimeField(null=True, verbose_name='Thời gian gửi')),
                ('content_type', models.TextField(blank=True, verbose_name='Loại nội dung')),
                ('status', models.IntegerField(choices=[(0, 'Die-YT'), (1, 'Banned-YT'), (2, 'Gov-YT'), (3, 'Live-YT'), (4, 'Link bị lỗi'), (5, 'Chưa xử lý')], default=5, verbose_name='Trạng thái')),
                ('checked_date', models.DateTimeField(auto_now=True, verbose_name='Thời điểm kiểm tra')),
            ],
            options={
                'verbose_name': 'Link Youtube',
                'verbose_name_plural': 'Link Youtube',
            },
        ),
    ]
