# Generated by Django 3.1.2 on 2020-10-24 08:00

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuuHo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('name', models.TextField(blank=True, default='', verbose_name='Đội cứu hộ')),
                ('status', models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Sẵn sàng'), (2, 'Không gọi được'), (5, 'Cần hỗ trợ'), (3, 'Đang cứu hộ'), (4, 'Đang nghỉ')], default=0, verbose_name='Tình trạng')),
                ('location', models.TextField(blank=True, default='', verbose_name='Phạm vi cứu hộ')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Các đội Cứu hộ',
                'verbose_name_plural': 'Các đội Cứu hộ',
            },
        ),
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Huyện')),
            ],
            options={
                'verbose_name': 'Thống kê Huyện',
                'verbose_name_plural': 'Thống kê Huyện',
            },
        ),
        migrations.CreateModel(
            name='Thon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Thôn')),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen')),
            ],
            options={
                'verbose_name': 'Thôn',
                'verbose_name_plural': 'Thôn',
            },
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Tỉnh')),
            ],
            options={
                'verbose_name': 'Thống kê Tỉnh',
                'verbose_name_plural': 'Thống kê Tỉnh',
            },
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', verbose_name='Tin')),
                ('url', models.TextField(blank=True, default='', verbose_name='Link')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Tin tức quan trọng ',
                'verbose_name_plural': 'Tin tức quan trọng ',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiHoDan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Tên trạng thái')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='Ngày tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Xã')),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen')),
            ],
            options={
                'verbose_name': 'Thống kê Xã',
                'verbose_name_plural': 'Thống kê Xã',
            },
        ),
        migrations.CreateModel(
            name='TinhNguyenVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Họ và tên')),
                ('status', models.IntegerField(choices=[(1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang nghỉ')], default=0, verbose_name='Tình trạng')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen')),
                ('thon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon')),
                ('tinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh')),
                ('xa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa')),
            ],
            options={
                'verbose_name': 'Tình nguyên viên thông tin',
                'verbose_name_plural': 'Tình nguyên viên thông tin',
            },
        ),
        migrations.CreateModel(
            name='NguonLuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Nguồn lực')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('status', models.IntegerField(choices=[(1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang nghỉ/Hết tài nguyên')], default=0, verbose_name='Tình trạng')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen')),
                ('thon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon')),
                ('tinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh')),
                ('xa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa')),
            ],
            options={
                'verbose_name': 'Nguồn trợ giúp khác',
                'verbose_name_plural': 'Nguồn trợ giúp khác',
            },
        ),
        migrations.AddField(
            model_name='huyen',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.CreateModel(
            name='HoDan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Hộ dân')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('people_number', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Số người')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('geo_location', app.models.CustomLocationField(blank=True, map_attrs={}, null=True)),
                ('cuuho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuuho', verbose_name='Đơn vị cứu hộ tiếp cận')),
                ('huyen', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.huyen')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trangthaihodan', verbose_name='Trạng thái')),
                ('thon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.thon')),
                ('tinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.tinh')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh')),
                ('xa', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.xa')),
            ],
            options={
                'verbose_name': 'Hộ dân cần ứng cứu',
                'verbose_name_plural': 'Hộ dân cần ứng cứu',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHoDan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.TextField(blank=True, default='', verbose_name='Hộ dân')),
                ('update_time', models.DateTimeField(blank=True, editable=False, verbose_name='Cập nhật')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('people_number', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Số người')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_time', models.DateTimeField(blank=True, editable=False, verbose_name='Ngày tạo')),
                ('geo_location', app.models.CustomLocationField(blank=True, map_attrs={}, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cuuho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.cuuho', verbose_name='Đơn vị cứu hộ tiếp cận')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('huyen', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.huyen')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.trangthaihodan', verbose_name='Trạng thái')),
                ('thon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.thon')),
                ('tinh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tinh')),
                ('volunteer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh')),
                ('xa', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.xa')),
            ],
            options={
                'verbose_name': 'historical Hộ dân cần ứng cứu',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.huyen'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='thon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.thon'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.tinh'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.xa'),
        ),
    ]
