# Generated by Django 3.0.3 on 2020-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời gian đăng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Thời gian gửi'),
        ),
    ]
