# Generated by Django 3.0.3 on 2020-09-14 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200914_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian đăng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian gửi'),
            preserve_default=False,
        ),
    ]
