# Generated by Django 3.0.8 on 2020-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200914_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish_date',
            field=models.DateField(null=True, verbose_name='Thời gian đăng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='send_date',
            field=models.DateField(null=True, verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Die-YT'), (1, 'Gov-YT'), (2, 'Gov-YT'), (3, 'Live-YT'), (4, 'Bad Link'), (5, 'Unchecked')], default=5, verbose_name='Trạng thái'),
        ),
    ]
