# Generated by Django 3.1.2 on 2020-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201006_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Bóc băng'),
        ),
    ]
