# Generated by Django 3.1.2 on 2020-10-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_contain', models.TextField(blank=True, verbose_name='Từ khoá cần chứa')),
                ('keyword_and', models.TextField(blank=True, verbose_name='Từ khoá đi kèm')),
                ('keyword_not', models.TextField(blank=True, verbose_name='Từ khoá loại trừ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='BadContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(blank=True, default='', verbose_name='Câu chứa nội dung xấu độc')),
                ('position', models.TextField(blank=True, default='')),
                ('violate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filter')),
            ],
        ),
    ]
