# Generated by Django 3.1.2 on 2020-10-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_badcontent_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contain_bad_content',
            field=models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Xấu độc'), (2, 'Bình thường')], default=0, verbose_name='Xấu độc'),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Kiểm tra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='send_date',
            field=models.DateField(null=True, verbose_name='Gửi'),
        ),
    ]
