# Generated by Django 3.1.2 on 2020-10-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201006_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.TextField(blank=True, verbose_name='Tên vi phạm'),
        ),
    ]
