# Generated by Django 3.1.2 on 2020-10-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_filter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Hành vi vi phạm', 'verbose_name_plural': 'Hành vi vi phạm'},
        ),
    ]
