# Generated by Django 3.1.2 on 2020-10-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_badcontent_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcontent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badcontent', to='app.item'),
        ),
    ]
