# Generated by Django 3.1.2 on 2020-10-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201006_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(blank=True, default='', verbose_name='Câu chứa nội dung xấu độc')),
                ('position', models.TextField(blank=True, default='')),
                ('contain_bad_content', models.BooleanField(default=False, verbose_name='Xấu độc?')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Tên kênh')),
                ('url', models.TextField(blank=True, default='', verbose_name='Channel Link')),
            ],
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Tên')),
                ('code_name', models.TextField(blank=True, default='', verbose_name='Mã')),
                ('position', models.TextField(blank=True, default='', verbose_name='Chức danh')),
                ('main_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá chính')),
                ('combine_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá kết hợp')),
                ('exclude_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá loại trừ')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.TextField(blank=True, default='', verbose_name='STT')),
                ('url', models.URLField(default='', null=True, verbose_name='Đường Link')),
                ('views', models.TextField(default='', verbose_name='Lượt xem')),
                ('publish_date', models.DateField(null=True, verbose_name='Thời gian đăng')),
                ('audio_path', models.TextField(blank=True, default='', verbose_name='Audio Filepath')),
                ('audio_link', models.TextField(blank=True, default='', verbose_name='Audio Link')),
                ('content', models.TextField(blank=True, default='', verbose_name='Bóc băng')),
                ('checked_date', models.DateTimeField(auto_now=True, verbose_name='Kiểm tra')),
                ('status', models.IntegerField(choices=[(0, 'Die-YT'), (1, 'Gov-YT'), (3, 'Live-YT'), (4, 'Bad Link'), (5, 'Unchecked')], default=5, verbose_name='Trạng thái')),
                ('group', models.TextField(blank=True, default='', verbose_name='Tên nhóm')),
                ('classify', models.TextField(blank=True, default='', verbose_name='Loại')),
                ('send_date', models.DateField(null=True, verbose_name='Gửi')),
                ('content_type', models.TextField(blank=True, verbose_name='Loại nội dung')),
                ('contain_bad_content', models.IntegerField(choices=[(0, 'Unchecked'), (1, 'Xấu độc'), (2, 'Bình thường')], default=0, verbose_name='Xấu độc')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.publisher', verbose_name='Chủ kênh')),
            ],
            options={
                'verbose_name': 'Link Youtube',
                'verbose_name_plural': 'Link Youtube',
            },
        ),
        migrations.RenameModel(
            old_name='Filter',
            new_name='Policy',
        ),
        migrations.DeleteModel(
            name='BadContent',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='badcase',
            name='violate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policy'),
        ),
        migrations.AddField(
            model_name='badcase',
            name='youtube_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badcontent', to='app.youtubeclip'),
        ),
    ]
