# Generated by Django 3.1.2 on 2020-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201010_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badcase',
            options={'verbose_name': 'Nội dung xấu độc', 'verbose_name_plural': 'Nội dung xấu độc'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Kênh giám sát', 'verbose_name_plural': 'Kênh giám sát'},
        ),
        migrations.AlterModelOptions(
            name='vip',
            options={'verbose_name': 'Danh sách VIP', 'verbose_name_plural': 'Danh sách VIP'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='video_count',
            field=models.IntegerField(default=0, verbose_name='Tổng số video'),
        ),
    ]
