# Generated by Django 3.1.2 on 2020-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201010_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='tracking',
            field=models.BooleanField(default=False, verbose_name='Đang giám sát?'),
        ),
    ]
