# Generated by Django 3.1.2 on 2020-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_publisher_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeclip',
            name='use_as_example',
            field=models.BooleanField(default=False, verbose_name='Dùng để huấn luyện AI?'),
        ),
    ]
