# Generated by Django 3.1.2 on 2020-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_youtubeclip_use_as_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeclip',
            name='stt',
        ),
        migrations.AddField(
            model_name='youtubeclip',
            name='title',
            field=models.TextField(default='', verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='youtubeclip',
            name='views',
            field=models.IntegerField(default='', verbose_name='Lượt xem'),
        ),
    ]
