# Generated by Django 3.1.2 on 2020-10-10 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201010_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='last_track_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Lần kiểm tra cuối'),
            preserve_default=False,
        ),
    ]
