# Generated by Django 3.1.2 on 2020-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_publisher_last_track_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeclip',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Độ dài (giây)'),
        ),
        migrations.AddField(
            model_name='youtubeclip',
            name='length_text',
            field=models.TextField(default='', verbose_name='Độ dài'),
        ),
        migrations.AddField(
            model_name='youtubeclip',
            name='views_text',
            field=models.TextField(default='', verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='youtubeclip',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
    ]
