# Generated by Django 3.1.2 on 2020-10-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201011_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipMentionExtraProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.youtubeclip_mentions',),
        ),
        migrations.AddField(
            model_name='youtubeclip',
            name='parse_sentence_for_training',
            field=models.BooleanField(default=False, verbose_name='Đã tách câu để dán nhãn?'),
        ),
        migrations.AlterField(
            model_name='youtubeclip',
            name='mentions',
            field=models.ManyToManyField(related_name='mention_clips', to='app.VIP', verbose_name='Đề cập tới'),
        ),
    ]
