# Generated by Django 3.1.2 on 2020-10-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201011_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badcase',
            name='violate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.policy'),
        ),
    ]
