# Generated by Django 3.1.2 on 2020-10-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201011_0429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badcase',
            options={'verbose_name': 'Từ điển Nội dung xấu độc', 'verbose_name_plural': 'Từ điển Nội dung xấu độc'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Từ điển Hành vi vi phạm', 'verbose_name_plural': 'Từ điển Hành vi vi phạm'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Quản lý Channel xấu độc', 'verbose_name_plural': 'Quản lý Channel xấu độc'},
        ),
        migrations.AlterModelOptions(
            name='vip',
            options={'verbose_name': 'Quản lý Danh sách VIP', 'verbose_name_plural': 'Quản lý Danh sách VIP'},
        ),
        migrations.AlterModelOptions(
            name='youtubeclip',
            options={'verbose_name': 'Quản lý clip Youtube', 'verbose_name_plural': 'Quản lý clip Youtube'},
        ),
        migrations.AddField(
            model_name='badcase',
            name='push_to_elasticsearch',
            field=models.BooleanField(default=False, verbose_name='Đã train ?'),
        ),
        migrations.AddField(
            model_name='badcase',
            name='use_as_example',
            field=models.BooleanField(default=False, verbose_name='Sử dụng để train AI'),
        ),
    ]
