# Generated by Django 3.1 on 2020-10-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201011_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Chủ đề xấu độc')),
                ('main_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá chính')),
                ('support_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá bổ sung')),
                ('exclude_keyword', models.TextField(blank=True, default='', verbose_name='Từ khoá loại trừ')),
            ],
        ),
        migrations.DeleteModel(
            name='VipMentionExtraProxy',
        ),
        migrations.AlterModelOptions(
            name='youtubeclip',
            options={'verbose_name': 'Quản lý Clip Youtube', 'verbose_name_plural': 'Quản lý Clip Youtube'},
        ),
        migrations.AlterField(
            model_name='badcase',
            name='violate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.policy', verbose_name='Vi phạm'),
        ),
        migrations.AlterField(
            model_name='badcase',
            name='youtube_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badcontent', to='app.youtubeclip', verbose_name='Link Youtube'),
        ),
    ]
