# Generated by Django 3.1 on 2020-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201011_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeclip',
            name='publish_date',
            field=models.DateTimeField(null=True, verbose_name='Thời gian đăng'),
        ),
    ]
