# Generated by Django 3.1 on 2020-10-12 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201012_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='badtopic',
            name='auto_add_publisher',
            field=models.BooleanField(default=True, verbose_name='Tự động thêm publisher?'),
        ),
        migrations.AddField(
            model_name='badtopic',
            name='last_track_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Lần kiểm tra cuối '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badtopic',
            name='result_filter',
            field=models.BooleanField(default=False, verbose_name='Lọc kết quả trả về?'),
        ),
        migrations.AddField(
            model_name='badtopic',
            name='search_keyword',
            field=models.TextField(blank=True, default='', verbose_name='Từ khoá tìm kiếm'),
        ),
        migrations.AddField(
            model_name='badtopic',
            name='tracking',
            field=models.BooleanField(default=False, verbose_name='Đang giám sát?'),
        ),
    ]
