# Generated by Django 3.1 on 2020-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20201012_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badtopic',
            name='last_track_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần kiểm tra cuối '),
        ),
    ]
