# Generated by Django 3.1 on 2020-10-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201012_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeclip',
            name='violate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.policy', verbose_name='Vi phạm'),
        ),
        migrations.AlterField(
            model_name='youtubeclip',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.publisher', verbose_name='Chủ kênh'),
        ),
    ]
