# Generated by Django 3.1.2 on 2020-10-14 01:41

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20201014_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='video_count_today',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_video_count_tody', default=0, editable=False, null=True, verbose_name='Video mới trong 24h qua'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='video_count',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_video_count', default=0, editable=False, null=True, verbose_name='Tổng số video'),
        ),
    ]
