# Generated by Django 3.1.2 on 2020-10-14 01:44

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201014_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='video_count_today',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_video_count_today', default=0, editable=False, null=True, verbose_name='Video mới trong 24h qua'),
        ),
    ]
