# Generated by Django 3.1.2 on 2020-10-14 03:48

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201014_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='video_count_week',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_video_count_week', default=0, editable=False, null=True, verbose_name='Video mới 1 tuần qua'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='video_count_today',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_video_count_today', default=0, editable=False, null=True, verbose_name='Video mới 24h qua'),
        ),
    ]
