# Generated by Django 3.1.2 on 2020-10-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20201014_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeclip',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_videos', to='app.badtopic', verbose_name='Nhóm chủ đề'),
        ),
    ]
