# Generated by Django 3.1.2 on 2020-10-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20201014_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuuHo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Đội cứu hộ')),
                ('status', models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang cứu hộ'), (4, 'Đang nghỉ')], default=0, verbose_name='Tình trạng')),
                ('location', models.TextField(blank=True, default='', verbose_name='Phạm vi cứu hộ')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
            ],
        ),
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Huyện')),
            ],
        ),
        migrations.CreateModel(
            name='Thon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Thôn')),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Tỉnh')),
            ],
        ),
        migrations.CreateModel(
            name='TinhNguyenVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Họ và tên')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('huyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen')),
                ('thon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon')),
                ('tinh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh')),
            ],
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', verbose_name='Xã')),
            ],
        ),
        migrations.RemoveField(
            model_name='youtubeclip',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='youtubeclip',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='youtubeclip',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='youtubeclip',
            name='violate',
        ),
        migrations.DeleteModel(
            name='BadCase',
        ),
        migrations.DeleteModel(
            name='BadTopic',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='VIP',
        ),
        migrations.DeleteModel(
            name='YoutubeClip',
        ),
        migrations.AddField(
            model_name='tinhnguyenvien',
            name='xa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='huyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='thon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh'),
        ),
        migrations.AddField(
            model_name='cuuho',
            name='xa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa'),
        ),
    ]
