# Generated by Django 3.1.2 on 2020-10-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_hodan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuuho',
            options={'verbose_name': 'Danh sách đội Cứu hộ', 'verbose_name_plural': 'Danh sách đội Cứu hộ'},
        ),
        migrations.AlterModelOptions(
            name='hodan',
            options={'verbose_name': 'Danh sách Hộ dân cần ứng cứu', 'verbose_name_plural': 'Danh sách Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name': 'Huyện', 'verbose_name_plural': 'Huyện'},
        ),
        migrations.AlterModelOptions(
            name='thon',
            options={'verbose_name': 'Thôn', 'verbose_name_plural': 'Thôn'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name': 'Tỉnh', 'verbose_name_plural': 'Tỉnh'},
        ),
        migrations.AlterModelOptions(
            name='tinhnguyenvien',
            options={'verbose_name': 'Danh sách Tình nguyên viên thông tin', 'verbose_name_plural': 'Danh sách Tình nguyên viên thông tin'},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name': 'Xã', 'verbose_name_plural': 'Xã'},
        ),
        migrations.AddField(
            model_name='tinhnguyenvien',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang nghỉ')], default=0, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='thon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='cuuho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cuuho', verbose_name='Đơn vị cứu hộ tiếp cận'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='thon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='thon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thon'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xa'),
        ),
    ]
