# Generated by Django 3.1.2 on 2020-10-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_nguonluc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodan',
            name='need',
            field=models.TextField(blank=True, default='', verbose_name='Nhu cầu'),
        ),
    ]
