# Generated by Django 3.1.2 on 2020-10-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20201019_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': 'Tin tức quan trọng ', 'verbose_name_plural': 'Tin tức quan trọng '},
        ),
    ]
