# Generated by Django 3.1.2 on 2020-10-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20201019_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name': 'Thống kê Huyện', 'verbose_name_plural': 'Thống kê Huyện'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name': 'Thống kê Tỉnh', 'verbose_name_plural': 'Thống kê Tỉnh'},
        ),
        migrations.AlterModelOptions(
            name='tinhnguyenvien',
            options={'verbose_name': 'Tình nguyên viên thông tin', 'verbose_name_plural': 'Tình nguyên viên thông tin'},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name': 'Thống kê Xã', 'verbose_name_plural': 'Thống kê Xã'},
        ),
    ]
