# Generated by Django 3.1.2 on 2020-10-20 07:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20201020_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='huyen',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tinh'),
        ),
        migrations.AddField(
            model_name='thon',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AddField(
            model_name='xa',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='app.huyen'),
        ),
    ]
