# Generated by Django 3.1.2 on 2020-10-20 09:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201020_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuuho',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='thon',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.thon'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.xa'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='thon',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.thon'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.xa'),
        ),
    ]
