# Generated by Django 3.1.2 on 2020-10-20 09:43

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201020_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.huyen'),
        ),
    ]
