# Generated by Django 3.1.2 on 2020-10-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20201020_1638'),
        ('app', '0049_auto_20201020_1643'),
    ]

    operations = [
    ]
