# Generated by Django 3.1.2 on 2020-10-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_merge_20201020_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodan',
            name='people_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Số người'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='thon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.thon'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.xa'),
        ),
    ]
