# Generated by Django 3.1.2 on 2020-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_merge_20201020_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodan',
            name='plus_code',
            field=models.TextField(blank=True, default='', verbose_name='Google Plus Code'),
        ),
    ]
