# Generated by Django 3.1.2 on 2020-10-21 23:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20201022_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodan',
            name='geo_location',
            field=app.models.CustomLocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='location',
            field=models.TextField(blank=True, default='', verbose_name='Địa chỉ'),
        ),
    ]
