# Generated by Django 3.1.2 on 2020-10-22 01:18

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0054_auto_20201022_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHoDan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.TextField(blank=True, default='', verbose_name='Hộ dân')),
                ('update_time', models.DateTimeField(blank=True, editable=False, verbose_name='Cập nhật')),
                ('location', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('status', models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Cần ứng cứu gấp'), (2, 'Không gọi được'), (3, 'Đã được cứu'), (4, 'Gặp nạn')], default=0, verbose_name='Tình trạng')),
                ('people_number', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Số người')),
                ('phone', models.TextField(blank=True, default='', verbose_name='Điện thoại liên hệ')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('geo_location', app.models.CustomLocationField(blank=True, map_attrs={}, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cuuho', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.cuuho', verbose_name='Đơn vị cứu hộ tiếp cận')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('huyen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.huyen')),
                ('thon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.thon')),
                ('tinh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tinh')),
                ('volunteer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tinhnguyenvien', verbose_name='Tình nguyện viên xác minh')),
                ('xa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.xa')),
            ],
            options={
                'verbose_name': 'historical Hộ dân cần ứng cứu',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
