# Generated by Django 3.1.2 on 2020-10-22 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20201022_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhodan',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hodan',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
    ]
