# Generated by Django 3.1.2 on 2020-10-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20201022_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodan',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
    ]
