# Generated by Django 3.1.2 on 2020-10-23 01:23

from django.db import migrations, models
import django.db.models.deletion

cap_nhat_trang_thai_ho_dan_sql = "\
/*\
Create new status in table app_trangthaihodan\
*/\
\
INSERT INTO app_trangthaihodan (id, name, created_time, update_time) VALUES\
(1, 'Chưa xác minh', NOW(), NOW()),\
(2, 'Không gọi được', NOW(), NOW()),\
(3, 'Cần ứng cứu gấp', NOW(), NOW()),\
(4, 'Đã gửi cứu hộ', NOW(), NOW()),\
(5, 'Cần thức ăn', NOW(), NOW()),\
(6, 'Cần thuốc men', NOW(), NOW()),\
(7, 'Đã an toàn', NOW(), NOW());\
\
/*\
Update app_hodan, set value of status_key_id based on status\
*/\
UPDATE app_hodan SET status_key_id = 1 WHERE status = 0;\
UPDATE app_hodan SET status_key_id = 2 WHERE status = 2;\
UPDATE app_hodan SET status_key_id = 3 WHERE status = 1 OR status = 4;\
UPDATE app_hodan SET status_key_id = 7 WHERE status = 3;\
UPDATE app_hodan SET status_key_id = 4 WHERE status = 5;\
UPDATE app_hodan SET status_key_id = 5 WHERE status = 6;\
UPDATE app_hodan SET status_key_id = 6 WHERE status = 7;\
UPDATE app_hodan SET status_key_id = 7 WHERE status = 8;\
\
/*\
Update app_hodan, set value of status based on status_key_id\
*/\
UPDATE app_hodan SET status = status_key_id;"


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20201023_0623'),
    ]

    operations = [
        # end pending trigger events
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunSQL(cap_nhat_trang_thai_ho_dan_sql),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
        # restart pending trigger events

        migrations.RemoveField(
            model_name='historicalhodan',
            name='status_key',
        ),
        migrations.RemoveField(
            model_name='hodan',
            name='status_key',
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.trangthaihodan', verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trangthaihodan', verbose_name='Trạng thái'),
        ),
    ]
