# Generated by Django 3.1.2 on 2020-10-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20201023_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhodan',
            name='status_key',
        ),
        migrations.RemoveField(
            model_name='hodan',
            name='status_key',
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.trangthaihodan', verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trangthaihodan', verbose_name='Trạng thái'),
        ),
    ]
