# Generated by Django 3.1.2 on 2020-10-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20201023_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhodan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Cần ứng cứu gấp'), (2, 'Không gọi được'), (3, 'Đã được cứu'), (4, 'Gặp nạn'), (5, 'Đã gửi cứu hộ'), (6, 'Cần thức ăn'), (7, 'Cần thuốc men'), (8, 'Đã ổn')], default=0, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Cần ứng cứu gấp'), (2, 'Không gọi được'), (3, 'Đã được cứu'), (4, 'Gặp nạn'), (5, 'Đã gửi cứu hộ'), (6, 'Cần thức ăn'), (7, 'Cần thuốc men'), (8, 'Đã ổn')], default=0, verbose_name='Tình trạng'),
        ),
    ]
