# Generated by Django 3.1.2 on 2020-10-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20201023_1017'),
        ('app', '0059_auto_20201023_0421'),
    ]

    operations = [
    ]
