# Generated by Django 3.1.2 on 2020-10-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20201023_0823'),
        ('app', '0062_merge_20201023_1230'),
    ]

    operations = [
    ]
