# Generated by Django 3.1.2 on 2020-10-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_merge_20201023_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuuho',
            name='huyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.huyen'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.tinh'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='xa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.xa'),
        ),
    ]
