# Generated by Django 3.1.2 on 2020-10-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_merge_20201023_1935'),
        ('app', '0063_auto_20201023_1441'),
    ]

    operations = [
    ]
