# Generated by Django 3.1.2 on 2020-10-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20201024_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuuho',
            options={'verbose_name': '2. Các đội Cứu hộ', 'verbose_name_plural': '2. Các đội Cứu hộ'},
        ),
        migrations.AlterModelOptions(
            name='historicalhodan',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 1. Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='hodan',
            options={'verbose_name': '1. Hộ dân cần ứng cứu', 'verbose_name_plural': '1. Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name': '4. Thống kê Huyện', 'verbose_name_plural': '4. Thống kê Huyện'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name': '3. Thống kê Tỉnh', 'verbose_name_plural': '3. Thống kê Tỉnh'},
        ),
        migrations.AlterModelOptions(
            name='tinhnguyenvien',
            options={'verbose_name': '7. Tình nguyên viên thông tin', 'verbose_name_plural': '7. Tình nguyên viên thông tin'},
        ),
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': '6. Tin tức quan trọng ', 'verbose_name_plural': '6. Tin tức quan trọng '},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name': '5. Thống kê Xã', 'verbose_name_plural': '5. Thống kê Xã'},
        ),
    ]
