# Generated by Django 3.1.2 on 2020-10-24 16:37

from django.db import migrations
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User

def create_token_for_all_users(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20201024_2337'),
    ]

    operations = [
        migrations.RunPython(create_token_for_all_users)
    ]
