# Generated by Django 3.1.2 on 2020-10-25 17:03

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20201024_2337'),
    ]

    operations = [
        UnaccentExtension()
    ]
