# Generated by Django 3.1.2 on 2020-10-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20201026_0003'),
        ('app', '0069_token'),
    ]

    operations = [
    ]
