# Generated by Django 3.1.2 on 2020-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_merge_20201027_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa xác minh'), (1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang nghỉ')], default=0, verbose_name='Tình trạng'),
        ),
    ]
