# Generated by Django 3.1.2 on 2020-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_merge_20201027_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTinh',
            fields=[
                ('name', models.TextField(blank=True, default='', verbose_name='Tỉnh')),
                ('prefix', models.TextField(blank=True, default='', null=True)),
                ('suffix', models.TextField(blank=True, default='', null=True)),
                ('long', models.TextField(blank=True, default='', null=True)),
                ('lat', models.TextField(blank=True, default='', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '3. Thống kê Tỉnh (new)',
                'verbose_name_plural': '3. Thống kê Tỉnh (new)',
            },
        ),
    ]
