# Generated by Django 3.1.2 on 2020-10-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20201031_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuuho',
            options={'verbose_name': 'Các đội Cứu hộ', 'verbose_name_plural': '2. Các đội Cứu hộ'},
        ),
        migrations.AlterModelOptions(
            name='historicalhodan',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='hodan',
            options={'verbose_name': 'Hộ dân cần ứng cứu', 'verbose_name_plural': '1. Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='tinhnguyenvien',
            options={'verbose_name': 'Tình nguyên viên thông tin', 'verbose_name_plural': '7. Tình nguyên viên thông tin'},
        ),
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': 'Tin tức quan trọng ', 'verbose_name_plural': '6. Tin tức quan trọng '},
        ),
    ]
