# Generated by Django 3.1.2 on 2020-10-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_newtinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHuyen',
            fields=[
                ('name', models.TextField(blank=True, default='', verbose_name='Huyện')),
                ('prefix', models.TextField(blank=True, default='', null=True)),
                ('suffix', models.TextField(blank=True, default='', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '4. Thống kê Huyện',
                'verbose_name_plural': '4. Thống kê Huyện',
            },
        ),
        migrations.RemoveField(
            model_name='newtinh',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='newtinh',
            name='long',
        ),
        migrations.AddField(
            model_name='newtinh',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newtinh',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NewXa',
            fields=[
                ('name', models.TextField(blank=True, default='', verbose_name='Xã')),
                ('prefix', models.TextField(blank=True, default='', null=True)),
                ('suffix', models.TextField(blank=True, default='', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newhuyen')),
            ],
            options={
                'verbose_name': '5. Thống kê Xã',
                'verbose_name_plural': '5. Thống kê Xã',
            },
        ),
        migrations.AddField(
            model_name='newhuyen',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newtinh'),
        ),
    ]
