# Generated by Django 3.1.2 on 2020-10-24 16:37

from django.db import migrations
import csv
from app.models import NewTinh, NewHuyen, NewXa
import os
DATA_DIR = os.path.dirname(os.path.realpath('project/app/data_files'))

def import_tinh_data(apps, schema_editor):
     with open('{}/tinh.csv'.format(DATA_DIR)) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            _, _ = NewTinh.objects.get_or_create(
                name = row[0],
                prefix = row[1],
                suffix = row[2],
                longitude = row[3],
                latitude = row[4],
                level = row[5],
                id = row[6],
                )

def import_huyen_data(apps, schema_editor):
     with open('{}/huyen.csv'.format(DATA_DIR)) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            _, _ = NewHuyen.objects.get_or_create(
                name = row[0],
                prefix = row[1],
                suffix = row[2],
                longitude = row[3],
                latitude = row[4],
                level = row[5],
                id = row[6],
                tinh_id = row[7],
                )

def import_xa_data(apps, schema_editor):
     with open('{}/xa.csv'.format(DATA_DIR)) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            _, _ = NewXa.objects.get_or_create(
                name = row[0],
                prefix = row[1],
                suffix = row[2],
                longitude = row[3],
                latitude = row[4],
                level = row[5],
                id = row[6],
                huyen_id = row[7],
                )

    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20201027_1848'),
    ]

    operations = [
        migrations.RunPython(import_tinh_data),
        migrations.RunPython(import_huyen_data),
        migrations.RunPython(import_xa_data),
    ]
