# Generated by Django 3.1.2 on 2020-10-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20201031_0338'),
        ('app', '0072_auto_20201031_1629'),
    ]

    operations = [
    ]
