# Generated by Django 3.1.2 on 2020-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_merge_20201031_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhodan',
            name='phone_expored',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hodan',
            name='phone_expored',
            field=models.TextField(blank=True, default=''),
        ),
    ]
