# Generated by Django 3.1.2 on 2020-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_merge_20201031_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhodan',
            name='do_quan_trong',
            field=models.IntegerField(choices=[(0, 'Cực kỳ quan trọng'), (1, 'Quan trọng'), (2, 'Ít quan trọng')], default=0, verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='trang_thai_lien_lac',
            field=models.IntegerField(choices=[(0, 'Không rõ'), (1, 'Liên lạc được'), (2, 'Không liên lạc được')], default=0, verbose_name='Trạng thái liên lạc'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='do_quan_trong',
            field=models.IntegerField(choices=[(0, 'Cực kỳ quan trọng'), (1, 'Quan trọng'), (2, 'Ít quan trọng')], default=0, verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='trang_thai_lien_lac',
            field=models.IntegerField(choices=[(0, 'Không rõ'), (1, 'Liên lạc được'), (2, 'Không liên lạc được')], default=0, verbose_name='Trạng thái liên lạc'),
        ),
    ]
