# Generated by Django 3.1.2 on 2020-11-11 21:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20201106_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuuho',
            options={'verbose_name': 'Các đội Cứu hộ', 'verbose_name_plural': 'Các đội Cứu hộ'},
        ),
        migrations.AlterModelOptions(
            name='hodan',
            options={'verbose_name': 'Hộ dân cần ứng cứu', 'verbose_name_plural': 'Hộ dân cần ứng cứu'},
        ),
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name': 'Thống kê Huyện', 'verbose_name_plural': 'Thống kê Huyện'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name': 'Thống kê Tỉnh', 'verbose_name_plural': 'Thống kê Tỉnh'},
        ),
        migrations.AlterModelOptions(
            name='tinhnguyenvien',
            options={'verbose_name': 'Tình nguyên viên thông tin', 'verbose_name_plural': 'Tình nguyên viên thông tin'},
        ),
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': 'Tin tức quan trọng ', 'verbose_name_plural': 'Tin tức quan trọng '},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name': 'Thống kê Xã', 'verbose_name_plural': 'Thống kê Xã'},
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='do_quan_trong',
            field=models.TextField(choices=[('P0', 'Cực kỳ quan trọng'), ('P1', 'Quan trọng'), ('P2', 'Ít quan trọng')], default='P1', help_text='Mức độ quan trọng', verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='nhu_cau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Danh sách nhu cầu cần thiết của hộ dân. Dùng dấu phẩy để ngăn cách các nhu cầu', null=True, size=None, verbose_name='Danh sách nhu cầu'),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='trang_thai_lien_lac',
            field=models.IntegerField(choices=[(0, 'Không rõ'), (1, 'Không liên lạc được'), (2, 'Liên lạc được')], default=0, help_text='Tình trạng liên lạc của hộ dân', verbose_name='Trạng Thái Liên Lạc'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='do_quan_trong',
            field=models.TextField(choices=[('P0', 'Cực kỳ quan trọng'), ('P1', 'Quan trọng'), ('P2', 'Ít quan trọng')], default='P1', help_text='Mức độ quan trọng', verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='nhu_cau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Danh sách nhu cầu cần thiết của hộ dân. Dùng dấu phẩy để ngăn cách các nhu cầu', null=True, size=None, verbose_name='Danh sách nhu cầu'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='trang_thai_lien_lac',
            field=models.IntegerField(choices=[(0, 'Không rõ'), (1, 'Không liên lạc được'), (2, 'Liên lạc được')], default=0, help_text='Tình trạng liên lạc của hộ dân', verbose_name='Trạng Thái Liên Lạc'),
        ),
        migrations.AlterField(
            model_name='nguonluc',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sẵn sàng'), (2, 'Không gọi được'), (3, 'Đang nghỉ/Hết tài nguyên')], default=1, verbose_name='Tình trạng'),
        ),
    ]
