# Generated by Django 3.1.2 on 2020-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20201109_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trangthaihodan',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Trạng thái sử dụng'),
        ),
    ]
