# Generated by Django 3.1.2 on 2020-11-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20201106_2122'),
        ('app', '0075_trangthaihodan_status'),
    ]

    operations = [
    ]
