# Generated by Django 3.1.2 on 2020-10-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_migrate_old_xa_data'),
        ('app', '0073_merge_20201031_1716'),
    ]

    operations = [
    ]
