# Generated by Django 3.1.2 on 2020-10-27 12:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_merge_20201031_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuuho',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.newhuyen'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.newtinh'),
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuuho_reversed', to='app.newxa'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.newhuyen'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='tinh',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.newtinh'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.newxa'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='huyen',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tinh', chained_model_field='tinh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.newhuyen'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.newtinh'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='xa',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='huyen', chained_model_field='huyen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hodan_reversed', to='app.newxa'),
        ),
        migrations.AlterField(
            model_name='nguonluc',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newhuyen'),
        ),
        migrations.AlterField(
            model_name='nguonluc',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newtinh'),
        ),
        migrations.AlterField(
            model_name='nguonluc',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newxa'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='huyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newhuyen'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newtinh'),
        ),
        migrations.AlterField(
            model_name='tinhnguyenvien',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newxa'),
        ),
    ]
