# Generated by Django 3.1.2 on 2020-10-24 16:37

from django.db import migrations
import csv
from app.models import NewTinh, NewHuyen, NewXa, HoDan, CuuHo
from django.db import models
import os

DATA_DIR = os.path.realpath('project/app/data_files/')

def migrate_huyen_id(apps, schema_editor):
    district_dict = {}
    with open('{}/map_district.csv'.format(DATA_DIR)) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            if row[1] != "null":
                district_dict[int(row[0])] = int(row[1])
            else:
                district_dict[int(row[0])] = None
    for hodan in HoDan.objects.all():
        if hodan.huyen_id is not None:
            hodan.huyen_id = district_dict.get(hodan.huyen_id, None)
            hodan.save()
    for cuuho in CuuHo.objects.all():
        if cuuho.huyen_id is not None:
            cuuho.huyen_id = district_dict.get(cuuho.huyen_id, None)
            cuuho.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_migrate_old_tinh_data'),
    ]

    operations = [
        # Remove foreign key before update
        migrations.AlterField(
            model_name='hodan',
            name='huyen_id',
            field=models.IntegerField(db_index=True, null=True)
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='huyen_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.RunPython(migrate_huyen_id),
        
    ]
