# Generated by Django 3.1.2 on 2020-11-13 15:01

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20201113_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhodan',
            name='geo_location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='geo_location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
