# Generated by Django 3.1.2 on 2020-10-24 16:37

from django.db import migrations
import csv
from app.models import NewTinh, NewHuyen, NewXa, HoDan, CuuHo, Xa
from django.db import models
from django.conf import settings

DATA_DIR = os.path.join(settings.BASE_DIR, 'app', 'data_files')

def migrate_xa_id(apps, schema_editor):
    for hodan in HoDan.objects.all():
        if hodan.xa_id is not None:
            flag = True
            current_xa = Xa.objects.get(pk=hodan.xa_id)
            matched_name_list = NewXa.objects.all().filter(name=current_xa.name)
            for new_xa in matched_name_list:
                if new_xa.huyen_id == hodan.huyen_id:
                    hodan.xa_id = new_xa.id
                    flag = False
                    break
            if flag == False:
                hodan.xa_id = None
            hodan.save()
                           
    for cuuho in CuuHo.objects.all():
        if cuuho.xa_id is not None:
            flag = True
            current_xa = Xa.objects.get(pk=cuuho.xa_id)
            matched_name_list = NewXa.objects.all().filter(name=current_xa.name)
            for new_xa in matched_name_list:
                if new_xa.huyen_id == cuuho.huyen_id:
                    cuuho.xa_id = new_xa.id
                    flag = False
                    break
            if flag == False:
                cuuho.xa_id = None
            cuuho.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_migrate_old_huyen_data'),
    ]

    operations = [
        # Remove foreign key before update
        migrations.AlterField(
            model_name='hodan',
            name='xa_id',
            field=models.IntegerField(db_index=True, null=True)
        ),
        migrations.AlterField(
            model_name='cuuho',
            name='xa_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.RunPython(migrate_xa_id),
    ]
