# Generated by Django 3.1.2 on 2020-11-13 15:34

import app.models
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20201113_2201'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='historicalhodan',
            name='geo_lat_lon',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={'geohash': '', 'lat': '', 'lng': ''}, null=True, verbose_name='Vị trí kinh vĩ độ'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='geo_lat_lon',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={'geohash': '', 'lat': '', 'lng': ''}, null=True, verbose_name='Vị trí kinh vĩ độ'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='do_quan_trong',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cực kỳ quan trọng'), (1, 'Rất quan trọng'), (2, 'Quan trọng'), (3, 'Ít quan trọng')], default=0, null=True, verbose_name='Độ quan trọng'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='geo_location',
            field=app.models.CustomLocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='hodan_nhucau',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cần di chuyển tới nơi an toàn'), (1, 'Cần thức ăn, nước uống'), (2, 'Cần thuốc men')], default=0, null=True, verbose_name='Nhu cầu'),
        ),
        migrations.AlterField(
            model_name='historicalhodan',
            name='trang_thai_lien_lac',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Không rõ'), (1, 'Liên lạc được'), (2, 'Không liên lạc được')], default=0, null=True, verbose_name='Tình trạng liên lạc'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='do_quan_trong',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cực kỳ quan trọng'), (1, 'Rất quan trọng'), (2, 'Quan trọng'), (3, 'Ít quan trọng')], default=0, null=True, verbose_name='Độ quan trọng'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='geo_location',
            field=app.models.CustomLocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='hodan_nhucau',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cần di chuyển tới nơi an toàn'), (1, 'Cần thức ăn, nước uống'), (2, 'Cần thuốc men')], default=0, null=True, verbose_name='Nhu cầu'),
        ),
        migrations.AlterField(
            model_name='hodan',
            name='trang_thai_lien_lac',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Không rõ'), (1, 'Liên lạc được'), (2, 'Không liên lạc được')], default=0, null=True, verbose_name='Tình trạng liên lạc'),
        ),
    ]
