# Generated by Django 3.1.2 on 2020-11-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20201114_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoDanDoQuanTrong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doquantrong_name', models.CharField(max_length=50, verbose_name='Độ quan trọng')),
                ('doquantrong_sort_index', models.SmallIntegerField(verbose_name='Thứ tự hiển thị')),
                ('doquantrong_created_time', models.DateTimeField(auto_now=True, verbose_name='Ngày tạo')),
                ('doquantrong_last_update_time', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('doquantrong_used_status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='HoDanLienLac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lienlac_name', models.CharField(max_length=50, verbose_name='Tình Trạng liên lạc')),
                ('lienlac_sort_index', models.SmallIntegerField(verbose_name='Thứ tự hiển thị')),
                ('lienlac_created_time', models.DateTimeField(auto_now=True, verbose_name='Ngày tạo')),
                ('lienlac_last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('lienlac_used_status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Sử dụng')),
            ],
        ),
        migrations.CreateModel(
            name='HoDanNhuCau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhucau_name', models.CharField(max_length=100, verbose_name='Nhu cầu')),
                ('nhucau_sort_index', models.SmallIntegerField(verbose_name='Thứ tự hiển thị')),
                ('nhucau_created_time', models.DateTimeField(auto_now=True, verbose_name='Ngày tạo')),
                ('nhucau_last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('nhucau_used_status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Sử dụng')),
            ],
        ),
        migrations.AlterField(
            model_name='trangthaihodan',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Sử dụng'),
        )
    ]
