# Generated by Django 3.1.2 on 2020-11-14 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20201114_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodandoquantrong',
            name='doquantrong_maker_color_code',
            field=models.CharField(default=1, max_length=18, verbose_name='Mã màu hiển thị cho độ quan trọng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trangthaihodan',
            name='trangthai_sort_index',
            field=models.SmallIntegerField(default=1, verbose_name='Thứ tự hiển thị'),
            preserve_default=False,
        )
    ]
