# Generated by Django 3.1.2 on 2020-11-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20201114_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhodan',
            name='do_quan_trong',
        ),
        migrations.RemoveField(
            model_name='historicalhodan',
            name='hodan_nhucau',
        ),
        migrations.RemoveField(
            model_name='historicalhodan',
            name='trang_thai_lien_lac',
        ),
        migrations.RemoveField(
            model_name='hodan',
            name='do_quan_trong',
        ),
        migrations.RemoveField(
            model_name='hodan',
            name='hodan_nhucau',
        ),
        migrations.RemoveField(
            model_name='hodan',
            name='trang_thai_lien_lac',
        ),
    ]
