# Generated by Django 3.1.2 on 2020-11-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20201114_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhodan',
            name='do_quan_trong',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.hodandoquantrong', verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='hodan_nhucau',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.hodannhucau', verbose_name='Nhu cầu'),
        ),
        migrations.AddField(
            model_name='historicalhodan',
            name='trang_thai_lien_lac',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.hodanlienlac', verbose_name='Tình trạng liên lạc'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='do_quan_trong',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hodandoquantrong', verbose_name='Độ quan trọng'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='hodan_nhucau',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hodannhucau', verbose_name='Nhu cầu'),
        ),
        migrations.AddField(
            model_name='hodan',
            name='trang_thai_lien_lac',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hodanlienlac', verbose_name='Tình trạng liên lạc'),
        ),
    ]
